services:
  main-app:
    env_file:
      - ./.env
    build:
      dockerfile: Dockerfile
    ports:
      - "${APP_VM_PORT}:${APP_DOCKER_PORT}"
    volumes:
      - type: bind
        source: ./models
        target: /churn_app/models

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    hostname: prometheus